# Generated by Django 6.0.5 on 2026-05-14 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laporan',
            options={'verbose_name_plural': 'Laporan Kinerja'},
        ),
        migrations.AddField(
            model_name='laporan',
            name='kategori',
            field=models.CharField(choices=[('Development', 'Development'), ('Maintenance', 'Maintenance'), ('Bug Fixing', 'Bug Fixing'), ('Research', 'Research')], default='Development', max_length=50),
        ),
        migrations.AddField(
            model_name='laporan',
            name='prioritas',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='laporan',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
