# Generated by Django 6.0.5 on 2026-05-14 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_profile_bagian_profile_foto_profile_jabatan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laporan',
            name='bagian',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='laporan',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
