# Generated by Django 6.0.5 on 2026-05-14 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_laporan_bagian_laporan_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='laporan',
            name='foto_progres',
            field=models.ImageField(blank=True, null=True, upload_to='progres_pics/'),
        ),
    ]
