# Generated by Django 6.0.5 on 2026-05-15 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_laporan_foto_progres'),
    ]

    operations = [
        migrations.AddField(
            model_name='laporan',
            name='estimasi_waktu',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='laporan',
            name='persentase',
            field=models.IntegerField(default=0),
        ),
    ]
