# Generated by Django 6.0.5 on 2026-05-15 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_laporan_estimasi_waktu_laporan_persentase'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laporan',
            options={'ordering': ['-updated_at'], 'verbose_name_plural': 'Laporan Kinerja'},
        ),
        migrations.AddField(
            model_name='laporan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='laporan',
            name='tanggal',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
