# Generated by Django 6.0.5 on 2026-05-15 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_laporan_options_laporan_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laporan',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
