# Generated by Django 6.0.5 on 2026-05-15 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_laporan_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laporan',
            name='foto_progres',
            field=models.FileField(blank=True, null=True, upload_to='progres_files/'),
        ),
    ]
