# Generated by Django 6.0.5 on 2026-05-15 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_laporan_foto_progres'),
    ]

    operations = [
        migrations.AddField(
            model_name='laporan',
            name='lampiran_admin',
            field=models.FileField(blank=True, null=True, upload_to='brief_files/'),
        ),
    ]
