# Generated by Django 6.0.5 on 2026-05-15 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_laporan_lampiran_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='laporan',
            name='link_project',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
