# Generated by Django 6.0.5 on 2026-05-31 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_laporan_link_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('hrd', 'HRD'), ('manager', 'Manager'), ('karyawan', 'Karyawan')], default='karyawan', max_length=20),
        ),
    ]
